version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    container_name: auth-manager
    expose:
      - '4000'
    ports:
      - '4000:4000'
    depends_on:
      - mongodb_container-dev
    command: npm run dev
  mongodb_container-dev:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: