version: '3'
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/usr/src/app
    container_name: auth-manager
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on:
      - mongodb_container-prod
    command: npm start
  mongodb_container-prod:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: